// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";
// import HomeHeader from "./component/HomeHeader";
// import Solidarity from "./component/Solidarity";
// import Registration from "./component/registration";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className="bg-[#14000b]">
//         <HomeHeader />
//         {children} <Registration />
//       </body>
//     </html>
//   );
// }

// 

// No "use client" here
import localFont from "next/font/local";
import "./globals.css";
import ClientLayout from "./ClientLayout" // your new client wrapper

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/Logo3.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#14000b]">
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}


// <HomeHeader
//           setWalletAddress={setWalletAddress}
//           walletAddress={walletAddress}
//         />
//         {children}
//         <Registration />
